/**
 * This class is used to format results. 
 * @author lbrod
 */
public class ResultConverter extends javax.swing.JFrame {

    /**
     * Creates new form ResultConverter
     */
    public ResultConverter() {
        initComponents();
        jTextArea1.setTabSize(12);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Result Formatter");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void convert(int n){
        String txt = jTextArea1.getText();
        String line[] = txt.split("\n");
        
        String out = "";
        
        int index = 1;
        boolean first = true;
        for(String s : line){
            if(index == 1){
                if(first){
                    out += s;
                    first = false;
                }else{
                    out += "\n" + s;
                }
            }else{
                out += "\t" + s;
            }
            index++;
            if(index == (n+1)){
                index = 1;
            }
        }
        jTextArea1.setText(out);        
    }    
    public void setText(String txt){
        jTextArea1.setText(txt);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
